/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.intuit.jaludden;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {

    @BeforeEach
    public void startServer() throws Exception {
    }

    @Test void shouldStartServer() throws Exception {
        var server = HolidayServer.createNull();
        var app = new App(server);
        app.start();
        assertTrue(server.isStarted());
    }
}
